### ISSUE TITLE
Version 0.16

### ISSUE THREAD

**Issue by EightBitRanger** [MakuraYami/factorio-mods#3]
Spawn Belt no longer works with Factorio version 0.16.

**Comment by MakuraYami** [comment]
Thanks for letting me know, I'll get on it and publish a fix soon.

**Comment by EightBitRanger** [comment]
Yeah no worries. Looks like someone else forked it in the meantime to get
it working and after trying it out, I don't notice any problems with spawn
belt <https://github.com/isitLoVe/factorio-mods/releases/tag/1.0.7> but the
rest of the mods might need updating as well.
https://github.com/isitLoVe/factorio-mods/releases/tag/1.0.7

**Comment by isitLoVe** [comment]
I did some minimal changes to get the mod working on 0.16.
However i have no knwledge on factorio mods so it would be nice if you update it "officially".

**Comment by MakuraYami** [comment]
Published the new version, took some suggestions from your fork @isitLoVe, thanks for that. I listed you as contributor in the mod's readme.

It's on the mod portal now, thanks for your interest everyone
