### ISSUE TITLE
cost-calc for 0.17

### ISSUE THREAD

**Issue by moppa** [MakuraYami/factorio-mods#4]
Any work being done to update the Cost Calc for 0.17?

**Comment by weep** [comment]
I've created a pull request with the updated recipes #5 
It requires validation thought

**Comment by barthuijgen** [comment]
Thank you for the PR, I had no idea this was still in use. I haven't been playing for a while awaiting the 1.0 release :) I will review it and make sure it is updated.

**Comment by MakuraYami** [comment]
Thank you for the PR, I had no idea this was still in use. I haven't been playing for a while awaiting the 1.0 release :) I will review it and make sure it is updated.

**Comment by MakuraYami** [comment]
The code has been merged, sorry for not using your PR, hope you don't mind :) Also set up deployments to https://storage.googleapis.com/factorio-cost-calc/index.html

I have not checked the validity of the recipes but I will revisit it once 0.17.x releases stable.
